<?php
/**
 * The template for displaying the footer
 *
 * Contains the closing of the #content div and all content after.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package Ruskitokot
 */

?>
	<div class="spotify">
		<h3 class="spotify__title">Miłego słuchania <i class="fas fa-smile"></i></h3>
		<button class="spotify__button"><i class="fab fa-spotify"></i></button>
		<!-- Spotify player generated by js -->
		<div id="spotify-player" class="spotify__player"></div>
	</div>

	</div><!-- #content -->

	<!-- footer -->
	<footer class="footer">
		<div class="container">
			<div class="row">
				<div class="col-12 col-sm-3 d-flex justify-content-center justify-content-sm-start">
					<a class="navbar-brand" href="<?php echo get_home_url(); ?>" title="<?php bloginfo('title'); ?>">
						<img src="<?php echo getTemplateUri()->img; ?>/ruski_logo.png" title="Ruski" alt="Ruskitokot logotyp">
					</a>
				</div>
				<div class="col-12 col-sm-9 d-flex align-items-center justify-content-center justify-content-sm-end">
					<p class="m-0">Realizacja: <strong>Maciej Tymosiak</strong></p>
					<a class="footer__realization-link navbar-brand mr-0 ml-4" href="https://www.e-raper.pl" title="E-raper.pl - Forum o rapie. Forum muzyczne. Polski rap." rel="sponsored" target="_blank">
						<img src="<?php echo getTemplateUri()->img; ?>/eraper.png" title="E-raper.pl - Forum o rapie" alt="E-raper - Polski rap">
					</a>
				</div>
			</div>
		</div>
	</footer>
	<!-- #footer -->
</div><!-- #page -->

<!--  SCRIPTS -->
<script src="<?php echo getTemplateUri()->dist; ?>/main.bundle.js"></script>

<?php wp_footer(); ?>
</body>
</html>
